[project]
build_number = 3
entry = "src/app.ts"
name = "Mango"
version = "1.1.6"

[project.icons]
source = "assets/icon.png"

[build]
opt_level = 2
out_dir = "dist"

[publish]
exclude = ["assets/screenshots", "test-screenshots", "tests", "logo"]

[i18n]
default_locale = "en"
locales = ["en", "de", "ja", "zh-Hans", "es-MX", "fr", "pt", "ko", "it", "tr", "th", "id", "vi"]

[audit]
ignore = [
    "hardcoded-secret",
    "sql-injection",
]

[macos]
bundle_id = "com.skelpo.mango"
distribute = "both"
encryption_exempt = true
entitlements = [
    "com.apple.security.app-sandbox",
    "com.apple.security.network.client",
]
notarize_signing_identity = "Developer ID Application: Skelpo GmbH"
signing_identity = "3rd Party Mac Developer Application: Skelpo GmbH (K6UW5YV9F7)"

[ios]
bundle_id = "com.skelpo.mango"
distribute = "testflight"
encryption_exempt = true
signing_identity = "Apple Distribution: Skelpo GmbH (K6UW5YV9F7)"

[android]
distribute = "playstore"
key_alias = "key0"

[linux]
format = "tarball"

[windows]
gcloud_kms_key = "projects/skelpo/locations/europe-west3/keyRings/code-signing-eu/cryptoKeys/skelpo-codesign/cryptoKeyVersions/1"
